version: '3.8'

services:
  mysql-db:
    image: mysql:8.0
    container_name: quebragalho_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: userapp
      MYSQL_DATABASE: quebragalho_db
    ports:
      - "3306:3306"
    cap_add:
      - SYS_NICE
